mod_name=Dynamic Trees The Twilight Forest
mod_id=dttwilightforest
mod_version=2.3.0-BETA01
mod_group_id=com.maxhyper.dttwilightforest
mod_license=MIT
mod_authors= Max Hyper
mod_description=Compatibility Mod between Dynamic Trees and The Twilight Forest

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.213
loader_version_range=[1,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true