modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-TheTwilightForest/issues"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/TheTwilightForest.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-the-twilight-forest"
#logoFile="examplemod.png"
credits="GroupiX05 for the 1.18.2, 1.19.2 and 1.20.1 ports"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="dynamictrees"
type="required"
versionRange="[1.5.0-BETA12,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="dynamictreesplus"
versionRange="[1.3.0-BETA02,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="twilightforest"
type="required"
versionRange="[4.7.0,)"
ordering="AFTER"
side="BOTH"